version: '3.7'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_db
      MYSQL_USER: mysql_usr
      MYSQL_PASSWORD: mysql_pass
    ports:
      - 3306:3306
    volumes:
      - "./mysql_data:/var/lib/mysql"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
